# Generated by Django 3.1.4 on 2020-12-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos')),
                ('image2', models.ImageField(upload_to='photos')),
                ('image3', models.ImageField(upload_to='photos')),
                ('image4', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
            ],
        ),
    ]
