# Generated by Django 3.1.4 on 2020-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shogproducts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.AddField(
            model_name='post',
            name='Discount',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
