# Generated by Django 3.1.4 on 2020-12-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shogproducts', '0002_auto_20201226_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Discount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
