# Generated by Django 3.1.4 on 2020-12-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shogproducts', '0003_auto_20201226_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Discount',
            field=models.CharField(blank=True, help_text='-20% discount', max_length=100),
        ),
    ]
